remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "default"
repository: "gene891212/gene891212.github.io"

author:
  name: "謝明"
  avatar: "https://github.com/gene891212.png"
  bio: "GitHub 專案展示與技術筆記"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/gene891212"

plugins:
  - jekyll-include-cache
  - jekyll-remote-theme
  - jekyll-github-metadata
  - jekyll-seo-tag

github: [metadata]